version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8787:8787"
    depends_on:
      - database
    environment:
      DATABASE_URI: mariadb://root@database/bot
      DATABASE_HOST: database
      DATABASE_USER: root
      WEB_PORT: 8787
      WEB_USERNAME: root

  database:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true